---
deployment:
  tasks:
    - export NODE_VERSION=18
    - source /opt/cpanel/ea-nodejs18/enable

    # Install dependencies
    - npm ci --silent

    # Build the Vite app
    - npm run build

    # Clean public_html
    - rm -rf /home/bengalsys/public_html/*

    # Deploy dist folder to public_html
    - cp -R dist/* /home/bengalsys/public_html/
